Fix issues with update-brickpi3-fw script
* Fix multiple board detection
* Fix board detection when BrickPi3 is not last board
* Fix RPi revision detection

diff --git a/script/update-brickpi3-fw b/script/update-brickpi3-fw
--- a/script/update-brickpi3-fw
+++ b/script/update-brickpi3-fw
@@ -4,15 +4,18 @@ set -e
 
 fw_file="/lib/firmware/brickpi3_firmware.bin"
 
-unset model
+unset match
 
 for board in /sys/class/board-info/*; do
+    model=$(cat $board/uevent | grep BOARD_INFO_MODEL= | cut -s -d = -f 2)
     if [ "$model" == "Dexter Industries BrickPi3" ]; then
-        echo "Error: More than one BrickPi3 is attached." 1>&2
-        exit 1
+	if [ -n "$match" ]; then
+	    echo "Error: More than one BrickPi3 is attached." 1>&2
+            exit 1
+	fi
+	match=$model
+        fw_ver=$(cat $board/uevent | grep BOARD_INFO_FW_VER= | cut -s -d = -f 2)
     fi
-    model=$(cat $board/uevent | grep BOARD_INFO_MODEL= | cut -s -d = -f 2 | tr -d [:space:])
-    fw_ver=$(cat $board/uevent | grep BOARD_INFO_MODEL= | cut -s -d = -f 2 | tr -d [:space:])
 done
 
 if [ "$model" != "Dexter Industries BrickPi3" ]; then
@@ -20,7 +23,7 @@ if [ "$model" != "Dexter Industries BrickPi3" ]; then
     exit 1
 fi
 
-revision=$(cat /proc/cpuinfo | grep Revision: | cut -s -d : -f 2 | tr -d [:space:])
+revision=$(cat /proc/cpuinfo | grep Revision | cut -s -d : -f 2 | tr -d [:space:])
 # Bit 23 means "new model" or something like that, not sure what other bits mean
 # https://github.com/raspberrypi/firmware/issues/705#issuecomment-339516857
 # just guessing for now
